drop table if exists keyval;
create table keyval (key text, val text);
insert into keyval (key, val) values('0No_Observation','No Observation');
insert into keyval (key, val) values('1.Grit','Grit');
insert into keyval (key, val) values('1.Loamy_Sand','Loamy Sand');
insert into keyval (key, val) values('1.Loose','Loose');
insert into keyval (key, val) values('1.Primary_Deposit','Primary deposit');
insert into keyval (key, val) values('1.Sand','Sand');
insert into keyval (key, val) values('1.Very_poorly_sorted','Very poorly sorted ');
insert into keyval (key, val) values('1_Fine_sand','Fine sand');
insert into keyval (key, val) values('2.Clay_Loam','Clay Loam');
insert into keyval (key, val) values('2.Friable','Friable');
insert into keyval (key, val) values('2.Loam','Loam');
insert into keyval (key, val) values('2.Low_Likely_Contaminated','Low likelihood low amount derived');
insert into keyval (key, val) values('2.Poorly_sorted','Poorly sorted');
insert into keyval (key, val) values('2.Sandy_Clay_Loam','Sandy Clay Loam');
insert into keyval (key, val) values('2.Sandy_Loam','Sandy Loam');
insert into keyval (key, val) values('2.Silt_Loam','Silt Loam');
insert into keyval (key, val) values('2.Silty_Clay_Loam','Silty Clay Loam');
insert into keyval (key, val) values('2.Small_Stones','Small Stones');
insert into keyval (key, val) values('2_Medium_Sand','Medium Sand');
insert into keyval (key, val) values('3.Clay','Clay');
insert into keyval (key, val) values('3.Crumbly','Crumbly');
insert into keyval (key, val) values('3.Large_stones','Large stones');
insert into keyval (key, val) values('3.Moderately_sorted','Moderately sorted');
insert into keyval (key, val) values('3.Possibly_Contaminated','Possibly Contaminated');
insert into keyval (key, val) values('3.Sandy_Clay','Sandy Clay');
insert into keyval (key, val) values('3.Silty_Clay','Silty Clay');
insert into keyval (key, val) values('3_Coarse_Sand','Coarse Sand');
insert into keyval (key, val) values('4.High_Likely_Contaminated','High likelihood high amount derived');
insert into keyval (key, val) values('4.Medium_Compact','Medium Compact');
insert into keyval (key, val) values('4.Sandy_Silt','Sandy Silt');
insert into keyval (key, val) values('4.Silt','Silt');
insert into keyval (key, val) values('4.Tauf','Tauf');
insert into keyval (key, val) values('4.Well_sorted','Well sorted');
insert into keyval (key, val) values('5.Compact','Compact');
insert into keyval (key, val) values('5.Contaminated','Contaminated');
insert into keyval (key, val) values('5.Midden','Midden');
insert into keyval (key, val) values('6.Concrete','Concrete');
insert into keyval (key, val) values('6.Medium_ribbon_(2.5-5cm_long)','Medium ribbon (2.5-5cm long)');
insert into keyval (key, val) values('6.Strong_ribbon','Strong ribbon');
insert into keyval (key, val) values('6.Weak_ribbon','Weak ribbon (less than 2.5cm long)');
insert into keyval (key, val) values('aChipped_Stone','Chipped Stone');
insert into keyval (key, val) values('Add_Date_Closed','Add Date Closed');
insert into keyval (key, val) values('Administrative','Administrative');
insert into keyval (key, val) values('aHand_pick','Hand-pick');
insert into keyval (key, val) values('Ambiguous','Ambiguous');
insert into keyval (key, val) values('Ambiguous','Ambiguous');
insert into keyval (key, val) values('Angular','Angular');
insert into keyval (key, val) values('Animal_Bone','Animal Bone');
insert into keyval (key, val) values('Animal_or_Plant','Animal/Plant');
insert into keyval (key, val) values('Animal_or_Plant_hole','Animal/Plant hole');
insert into keyval (key, val) values('Arbitrary','Arbitrary');
insert into keyval (key, val) values('Arbitrary_Spit','ArbitrarySpit');
insert into keyval (key, val) values('Arch_Soil','Arch Soil');
insert into keyval (key, val) values('Area_Code','Area Code');
insert into keyval (key, val) values('AreaCode','AreaCode');
insert into keyval (key, val) values('Artefact','Artefact');
insert into keyval (key, val) values('Artefact_Class','Artefact Class');
insert into keyval (key, val) values('Artefact_cluster','Artefact Cluster');
insert into keyval (key, val) values('Artefact_Group','Artefact Cluster');
insert into keyval (key, val) values('Artefact_Group_Comment','Artefact Cluster Comment');
insert into keyval (key, val) values('Artefact_Group_ID','Artefact Cluster ID');
insert into keyval (key, val) values('Artefact_Quantity','Artefact Quantity');
insert into keyval (key, val) values('Artefact_Weight','Artefact Weight');
insert into keyval (key, val) values('Artefacts','Artefacts');
insert into keyval (key, val) values('Artifact_cluster','Artifact Cluster');
insert into keyval (key, val) values('Ash','Ash');
insert into keyval (key, val) values('Ash_or_Charcoal','Ash/Charcoal');
insert into keyval (key, val) values('Ashlar','Ashlar');
insert into keyval (key, val) values('Associations','Associations');
insert into keyval (key, val) values('Attach_Sketch','Attach Sketch');
insert into keyval (key, val) values('Attached_Audio_Files','Attached Audio Files');
insert into keyval (key, val) values('Attached_Photos','Attached Photos');
insert into keyval (key, val) values('Attached_Videos','Attached Videos');
insert into keyval (key, val) values('Attachments','Attachments');
insert into keyval (key, val) values('aVertical','Vertical');
insert into keyval (key, val) values('b45-90_degrees','Between 45 and 90 degrees from horizontal');
insert into keyval (key, val) values('Bead','Bead');
insert into keyval (key, val) values('Beam','Beam');
insert into keyval (key, val) values('bGround_Stone','Ground Stone');
insert into keyval (key, val) values('Bin','Bin');
insert into keyval (key, val) values('Black','Black');
insert into keyval (key, val) values('Blade','Blade');
insert into keyval (key, val) values('Blunt','Blunt');
insert into keyval (key, val) values('Boat_shaped','Boat shaped');
insert into keyval (key, val) values('Bond_Type','Bond Type');
insert into keyval (key, val) values('Bonding','Bonding/Packing');
insert into keyval (key, val) values('Bonding_Details','Bonding Details');
insert into keyval (key, val) values('BondingPacking_Details','Bonding/Packing details');
insert into keyval (key, val) values('Bone','Bone');
insert into keyval (key, val) values('Break_of_slope_-_Base','Break of slope - Base');
insert into keyval (key, val) values('Break_of_Slope_-_Top','Break of Slope - Top');
insert into keyval (key, val) values('Brick','Brick');
insert into keyval (key, val) values('Broken','Broken');
insert into keyval (key, val) values('bTrowel','Trowel');
insert into keyval (key, val) values('Building','Building');
insert into keyval (key, val) values('Building','Building');
insert into keyval (key, val) values('Building','Building');
insert into keyval (key, val) values('Building_Materials','Building Materials');
insert into keyval (key, val) values('Burial','Burial');
insert into keyval (key, val) values('Burial','Burial');
insert into keyval (key, val) values('C14_Sample','C14 Sample');
insert into keyval (key, val) values('c45_degrees','45 degrees');
insert into keyval (key, val) values('Cache','Cache');
insert into keyval (key, val) values('cBone','Bone');
insert into keyval (key, val) values('Cement_mortar','Cement mortar');
insert into keyval (key, val) values('Ceramic','Ceramic');
insert into keyval (key, val) values('Charcoal','Charcoal');
insert into keyval (key, val) values('Charred_Seed','Charred Seed');
insert into keyval (key, val) values('Chinking_stones','Chinking stones');
insert into keyval (key, val) values('Circular','Circular');
insert into keyval (key, val) values('Clay','Clay');
insert into keyval (key, val) values('Clay_Loam','Clay Loam');
insert into keyval (key, val) values('Clear','Clear');
insert into keyval (key, val) values('Clear','Clear');
insert into keyval (key, val) values('Coarse-grained_sediments','Coarse-grained sediments');
insert into keyval (key, val) values('Coarse','Coarse');
insert into keyval (key, val) values('Coarse_Pebbles','Coarse Pebbles');
insert into keyval (key, val) values('Cobbles','Cobbles');
insert into keyval (key, val) values('Collection_Method','Collection Method');
insert into keyval (key, val) values('Colour_and_material','Colour and material');
insert into keyval (key, val) values('Coloured','Coloured');
insert into keyval (key, val) values('Colourless','Colourless');
insert into keyval (key, val) values('Compact','Compact');
insert into keyval (key, val) values('Compact_laminated','Compact laminated');
insert into keyval (key, val) values('Compact_Laminated','Compact Laminated');
insert into keyval (key, val) values('Component','Component');
insert into keyval (key, val) values('Component_Finish','Prep/Dressing');
insert into keyval (key, val) values('Component_Type','Component Type');
insert into keyval (key, val) values('Composition_Type','Deposit Structure');
insert into keyval (key, val) values('Concave','Concave');
insert into keyval (key, val) values('Construction_Cut','Construction Cut');
insert into keyval (key, val) values('Contamination','Contamination');
insert into keyval (key, val) values('Context','Context');
insert into keyval (key, val) values('Context_Comments','Context Comments');
insert into keyval (key, val) values('Context_Feature_ID','Context/Feature ID');
insert into keyval (key, val) values('Context_Group','Feature');
insert into keyval (key, val) values('Context_Group_ID','Feature ID');
insert into keyval (key, val) values('Context_Groups','Features');
insert into keyval (key, val) values('Context_ID','Context ID');
insert into keyval (key, val) values('Context_Name','Brief Description');
insert into keyval (key, val) values('Context_Number','Context Code');
insert into keyval (key, val) values('Context_Type','Context Type');
insert into keyval (key, val) values('Contexts','Contexts');
insert into keyval (key, val) values('Convex','Convex');
insert into keyval (key, val) values('Copper-alloy','Copper-alloy');
insert into keyval (key, val) values('Core','Core');
insert into keyval (key, val) values('cPick','Pick');
insert into keyval (key, val) values('Cut','Negative Element');
insert into keyval (key, val) values('Cut_Function','Cut Function');
insert into keyval (key, val) values('Cuts','Negative Elements');
insert into keyval (key, val) values('Date_Closed','Completed');
insert into keyval (key, val) values('Date_Closed','Date Closed');
insert into keyval (key, val) values('Date_Opened','Date Opened');
insert into keyval (key, val) values('Date_Opened','Date started');
insert into keyval (key, val) values('Delete.Record','Delete Record');
insert into keyval (key, val) values('Deposit','Deposit');
insert into keyval (key, val) values('Deposit_Bedding','Bedding');
insert into keyval (key, val) values('Deposit_Inclusions','Deposit Inclusions');
insert into keyval (key, val) values('Deposit_Thickness_&amp;_Extent','Deposit Thickness & Extent');
insert into keyval (key, val) values('Deposit_Thickness_and_Extent','Deposit Thickness & Extent');
insert into keyval (key, val) values('Deposit_Volume','Volume (L)');
insert into keyval (key, val) values('Deposits','Deposits');
insert into keyval (key, val) values('Depth','Depth (m)');
insert into keyval (key, val) values('Devices','Devices');
insert into keyval (key, val) values('Diffuse','Diffuse');
insert into keyval (key, val) values('Distinct_floor_contact','Distinct floor contact');
insert into keyval (key, val) values('Distinguishing_Marks','Distinguishing Marks');
insert into keyval (key, val) values('Ditch_or_Trench','Ditch/Trench');
insert into keyval (key, val) values('dless_than_45','Less than 45 degrees from horizontal');
insert into keyval (key, val) values('Does_NOT_feel_very_gritty','Does NOT feel very gritty');
insert into keyval (key, val) values('Does_NOT_form_a_ribbom','Does NOT form a ribbom');
insert into keyval (key, val) values('dOther','Other');
insert into keyval (key, val) values('Doubtful','Doubtful');
insert into keyval (key, val) values('Dressed_Stone','Dressed Stone');
insert into keyval (key, val) values('Dressed_stones','Dressed stones');
insert into keyval (key, val) values('Dry-pressed','Dry-pressed');
insert into keyval (key, val) values('dShell','Shell');
insert into keyval (key, val) values('Dump','Dump');
insert into keyval (key, val) values('E-W','E-W');
insert into keyval (key, val) values('Earth','Earth');
insert into keyval (key, val) values('Elongated_oval','Elongated oval');
insert into keyval (key, val) values('End_date','End Date');
insert into keyval (key, val) values('English_Bond','English Bond');
insert into keyval (key, val) values('ePlant','Plant');
insert into keyval (key, val) values('Erosional_Feature','Erosional Feature');
insert into keyval (key, val) values('Erosional_products','Erosional products');
insert into keyval (key, val) values('Excavated_By','Excavated By');
insert into keyval (key, val) values('Excavation_Method','Excavation Method');
insert into keyval (key, val) values('Export_Liverpool','Export (Liverpool)');
insert into keyval (key, val) values('Export_Turkey','Export (Turkey)');
insert into keyval (key, val) values('External','External');
insert into keyval (key, val) values('External','External');
insert into keyval (key, val) values('Feature','Feature');
insert into keyval (key, val) values('Feels_very_gritty','Feels very gritty');
insert into keyval (key, val) values('Feels_very_smooth','Feels very smooth');
insert into keyval (key, val) values('Ferrous','Ferrous');
insert into keyval (key, val) values('Figurine','Figurine');
insert into keyval (key, val) values('Fine-grained_sediments','Fine-grained sediments');
insert into keyval (key, val) values('Fine','Fine');
insert into keyval (key, val) values('Fine_Pebbles','Fine Pebbles');
insert into keyval (key, val) values('Firm','Firm');
insert into keyval (key, val) values('Flat','Flat');
insert into keyval (key, val) values('Flemish_Bond','Flemish Bond');
insert into keyval (key, val) values('Floor','Floor');
insert into keyval (key, val) values('Floor_or_Surface','Floor/Surface');
insert into keyval (key, val) values('Flot_Sample','Flot Sample');
insert into keyval (key, val) values('fOchre','Ochre');
insert into keyval (key, val) values('Forms_ribbon','Forms ribbon');
insert into keyval (key, val) values('Foundation_trench','Foundation trench');
insert into keyval (key, val) values('Foundation_Trench_Fill','Foundation Trench Fill');
insert into keyval (key, val) values('Friable','Friable');
insert into keyval (key, val) values('Garden_loam','Garden loam');
insert into keyval (key, val) values('Glass','Glass');
insert into keyval (key, val) values('Glazed_brick','Glazed brick');
insert into keyval (key, val) values('Gradual','Gradual');
insert into keyval (key, val) values('Grid_Location_Reference','Grid');
insert into keyval (key, val) values('Grid_X','Grid X');
insert into keyval (key, val) values('Grid_Y','Grid Y');
insert into keyval (key, val) values('Grinder','Grinder');
insert into keyval (key, val) values('Ground','Ground');
insert into keyval (key, val) values('Hackberry','Hackberry');
insert into keyval (key, val) values('Hand_collection','Hand collection');
insert into keyval (key, val) values('Hard','Hard');
insert into keyval (key, val) values('hClay_Object','Clay Object');
insert into keyval (key, val) values('Header_Bond','Header Bond');
insert into keyval (key, val) values('Hearth','Hearth');
insert into keyval (key, val) values('Hearth_or_Fire_pit','Hearth/Fire pit');
insert into keyval (key, val) values('Heterogeneous','Heterogeneous');
insert into keyval (key, val) values('Highest_Level','Abs Ht Top (m)');
insert into keyval (key, val) values('Homogenous','Homogenous');
insert into keyval (key, val) values('Horizon_Boundary','Basal Edge Definition ');
insert into keyval (key, val) values('Horizontal','Horizontal');
insert into keyval (key, val) values('Human_Bone','Human Bone');
insert into keyval (key, val) values('iCeramic','Ceramic');
insert into keyval (key, val) values('Impression_Cast','Impression Cast');
insert into keyval (key, val) values('Incised_Stone','Incised Stone');
insert into keyval (key, val) values('Inclination_of_axis','Inclination of axis');
insert into keyval (key, val) values('Inclusion','Inclusions');
insert into keyval (key, val) values('Indeterminate','Indeterminate');
insert into keyval (key, val) values('Indurated','Indurated');
insert into keyval (key, val) values('Internal','Internal');
insert into keyval (key, val) values('Interpretation','Interpretation');
insert into keyval (key, val) values('Irregular','Irregular');
insert into keyval (key, val) values('Is_too_dry','Is too dry');
insert into keyval (key, val) values('Is_too_wet','Is too wet');
insert into keyval (key, val) values('jGlass','Glass');
insert into keyval (key, val) values('kMetal','Metal');
insert into keyval (key, val) values('Laminated','Laminated');
insert into keyval (key, val) values('lBuilding_Materials','Building Materials');
insert into keyval (key, val) values('Length','Length (m)');
insert into keyval (key, val) values('Levelling_Fill','Makeup/Levelling');
insert into keyval (key, val) values('Lime-shell_mortar','Lime-shell mortar');
insert into keyval (key, val) values('Linear','Linear');
insert into keyval (key, val) values('Loam','Loam');
insert into keyval (key, val) values('Loamy_Sand','Loamy Sand');
insert into keyval (key, val) values('Location_Note','Approx location in area');
insert into keyval (key, val) values('Loose','Loose');
insert into keyval (key, val) values('Lowest_Level','Abs Ht Bottom (m)');
insert into keyval (key, val) values('Matrices','Sediments/Aggregates');
insert into keyval (key, val) values('Matrix','Sediment/Aggregate');
insert into keyval (key, val) values('Medium_Pebbles','Medium Pebbles');
insert into keyval (key, val) values('Medium_ribbon_(2.5-5cm_long)','Medium ribbon (2.5-5cm long)');
insert into keyval (key, val) values('Merging','Merging');
insert into keyval (key, val) values('Metal','Metal');
insert into keyval (key, val) values('Mid_X','Mid X');
insert into keyval (key, val) values('Mid_X','Mid X');
insert into keyval (key, val) values('Mid_Y','Mid Y');
insert into keyval (key, val) values('Mid_Y','Mid Y');
insert into keyval (key, val) values('Midden','Midden');
insert into keyval (key, val) values('mMiscellaneous','Miscellaneous');
insert into keyval (key, val) values('Mortar','Mortar');
insert into keyval (key, val) values('Mud_mortar','Mud mortar');
insert into keyval (key, val) values('Mud_or_Plaster_Face','Mud/Plaster Face');
insert into keyval (key, val) values('Mudbrick','Mudbrick');
insert into keyval (key, val) values('Mudbrick_Shape','Mudbrick Shape');
insert into keyval (key, val) values('Mudbrick_Shape','Mudbrick Shape(s)');
insert into keyval (key, val) values('N-S','N-S');
insert into keyval (key, val) values('Natural','Natural');
insert into keyval (key, val) values('NE-SW','NE-SW');
insert into keyval (key, val) values('Neither_very_gritty_nor_very_smooth','Neither very gritty nor very smooth');
insert into keyval (key, val) values('No','No');
insert into keyval (key, val) values('NO_RESULT:_add_dry_soil_and_start_again','NO RESULT: add dry soil and start again');
insert into keyval (key, val) values('NO_RESULT:_add_more_water_and_start_again','NO RESULT: add more water and start again');
insert into keyval (key, val) values('Not_perceptible','Not perceptible');
insert into keyval (key, val) values('Not_sure','Not sure');
insert into keyval (key, val) values('NOT_too_wet_nor_too_dry','NOT too wet nor too dry');
insert into keyval (key, val) values('Number_Courses','Number of courses');
insert into keyval (key, val) values('NW-SE','NW-SE');
insert into keyval (key, val) values('Oblique_shallow','Oblique shallow');
insert into keyval (key, val) values('Oblique_steep','Oblique steep');
insert into keyval (key, val) values('Organic','Organic');
insert into keyval (key, val) values('Orientation','Orientation');
insert into keyval (key, val) values('Other','Other');
insert into keyval (key, val) values('Oven','Oven');
insert into keyval (key, val) values('Ovoid','Ovoid');
insert into keyval (key, val) values('Ovoid','Ovoid');
insert into keyval (key, val) values('Packing','Packing');
insert into keyval (key, val) values('Painted_plaster','Painted plaster');
insert into keyval (key, val) values('Partly_naturally_derived','Partly naturally derived');
insert into keyval (key, val) values('Paving','Paving');
insert into keyval (key, val) values('Peat','Peat');
insert into keyval (key, val) values('Pendant','Pendant');
insert into keyval (key, val) values('Percentage','Percentage');
insert into keyval (key, val) values('Pestle','Pestle');
insert into keyval (key, val) values('Phase_From','Phase From');
insert into keyval (key, val) values('Phase_To','Phase To');
insert into keyval (key, val) values('Photo','Photo');
insert into keyval (key, val) values('Photograph_Log','Photograph Register');
insert into keyval (key, val) values('Phytolith','Phytolith');
insert into keyval (key, val) values('Phytolith_Sample','Phytolith Sample');
insert into keyval (key, val) values('Pillar','Pillar');
insert into keyval (key, val) values('Pit','Pit');
insert into keyval (key, val) values('Pit_Fill','Pit Fill');
insert into keyval (key, val) values('placeholder','placeholder');
insert into keyval (key, val) values('Plank','Plank');
insert into keyval (key, val) values('Plano_convex','Plano-convex');
insert into keyval (key, val) values('Plans','Plans');
insert into keyval (key, val) values('Plaster','Plaster');
insert into keyval (key, val) values('Plastic','Plastic');
insert into keyval (key, val) values('Platform_or_Bench','Platform/Bench');
insert into keyval (key, val) values('Point','Point');
insert into keyval (key, val) values('Pointed','Pointed');
insert into keyval (key, val) values('Polished_plaster','Polished plaster');
insert into keyval (key, val) values('Polisher','Polisher');
insert into keyval (key, val) values('Post','Post');
insert into keyval (key, val) values('Posthole','Posthole');
insert into keyval (key, val) values('Posthole','Posthole');
insert into keyval (key, val) values('Quoins_stressed','Quoins stressed');
insert into keyval (key, val) values('Random_coursed','Random coursed');
insert into keyval (key, val) values('Random_uncoursed','Random uncoursed');
insert into keyval (key, val) values('Record_Audio','Record Audio');
insert into keyval (key, val) values('Record_Video','Record Video');
insert into keyval (key, val) values('Recorded_By','Recorded By');
insert into keyval (key, val) values('Rectangular','Rectangular');
insert into keyval (key, val) values('Rectangular','Rectangular');
insert into keyval (key, val) values('Regular_courses','Regular courses');
insert into keyval (key, val) values('Relationships_to_Other_Contexts','Relationships to Other Contexts');
insert into keyval (key, val) values('Room','Room');
insert into keyval (key, val) values('Roughly-hewn','Roughly-hewn');
insert into keyval (key, val) values('Rounded','Rounded');
insert into keyval (key, val) values('Rubbish_Pit','Rubbish Pit');
insert into keyval (key, val) values('Rubbish_Pit_Fill','Rubbish Pit Fill');
insert into keyval (key, val) values('Rubble','Rubble');
insert into keyval (key, val) values('Sample','Sample');
insert into keyval (key, val) values('Sample_Comments','Sample Comments');
insert into keyval (key, val) values('Sample_ID','Sample ID');
insert into keyval (key, val) values('Sample_Location','Sample Location');
insert into keyval (key, val) values('Sample_Type','Sample Type');
insert into keyval (key, val) values('Sample_Volume','Sample Volume (L)');
insert into keyval (key, val) values('Sample_Weight','Sample Weight (g)');
insert into keyval (key, val) values('Samples','Samples');
insert into keyval (key, val) values('Sand','Sand');
insert into keyval (key, val) values('Sandstock','Sandstock');
insert into keyval (key, val) values('Sandy_Clay','Sandy Clay');
insert into keyval (key, val) values('Sandy_Clay_Loam','Sandy Clay Loam');
insert into keyval (key, val) values('Sandy_Loam','Sandy Loam');
insert into keyval (key, val) values('Save.Record','Save Record');
insert into keyval (key, val) values('Section_Numbers','Section Numbers');
insert into keyval (key, val) values('Semi-Circular','Semi-Circular');
insert into keyval (key, val) values('Set_Cut','Set in Cut');
insert into keyval (key, val) values('Shaft_Straightener','Shaft Straightener');
insert into keyval (key, val) values('Shallow','Shallow');
insert into keyval (key, val) values('Shape_of_Base','Shape of Base');
insert into keyval (key, val) values('Shape_of_Corners','Shape of Corners');
insert into keyval (key, val) values('Shape_of_Cut','Shape in Plan');
insert into keyval (key, val) values('Shape_of_Cut_-_Note','Shape of Cut - Note');
insert into keyval (key, val) values('Sharp','Sharp');
insert into keyval (key, val) values('Shell','Shell');
insert into keyval (key, val) values('Sides_of_Cut','Shape in Section');
insert into keyval (key, val) values('Siliceous_Material','Siliceous Material');
insert into keyval (key, val) values('Silt','Silt');
insert into keyval (key, val) values('Silt_Loam','Silt Loam');
insert into keyval (key, val) values('Silty_Clay','Silty Clay');
insert into keyval (key, val) values('Silty_Clay_Loam','Silty Clay Loam');
insert into keyval (key, val) values('Silty_Loam','Silty Loam');
insert into keyval (key, val) values('Site_Code','Site Code');
insert into keyval (key, val) values('Site_depot','Site depot');
insert into keyval (key, val) values('Skeleton','Skeleton');
insert into keyval (key, val) values('Skeleton_Body','Body');
insert into keyval (key, val) values('Skeleton_Condition','Condition');
insert into keyval (key, val) values('Skeleton_Days_Exposed','Number of days exposed');
insert into keyval (key, val) values('Skeleton_Dimensions','Dimensions');
insert into keyval (key, val) values('Skeleton_Environment','Condition and Weather');
insert into keyval (key, val) values('Skeleton_Head','Head');
insert into keyval (key, val) values('Skeleton_Left_Arm','Left arm and hand location');
insert into keyval (key, val) values('Skeleton_Left_Leg','Left leg and foot location');
insert into keyval (key, val) values('Skeleton_Notes','Skeleton Notes');
insert into keyval (key, val) values('Skeleton_Right_Arm','Right arm and hand location');
insert into keyval (key, val) values('Skeleton_Right_Leg','Right leg and foot location');
insert into keyval (key, val) values('Skeleton_Surface_Modifications','Surface Modifications');
insert into keyval (key, val) values('Sketch','Sketch');
insert into keyval (key, val) values('Slag','Slag');
insert into keyval (key, val) values('Slightly_sloping','Slightly Sloping');
insert into keyval (key, val) values('Sloping','Sloping');
insert into keyval (key, val) values('Smooth','Smooth');
insert into keyval (key, val) values('Smoothed_plaster','Smoothed plaster');
insert into keyval (key, val) values('Soft','Soft');
insert into keyval (key, val) values('Soil','Soil');
insert into keyval (key, val) values('Soil_Colour','Soil Colour');
insert into keyval (key, val) values('Soil_Compaction_Description','Texture Description');
insert into keyval (key, val) values('Soil_Compaction_Type','Texture');
insert into keyval (key, val) values('Soil_does_NOT_remain_in_ball_when_squeezed','Soil does NOT remain in ball when squeezed       ');
insert into keyval (key, val) values('Soil_Grain_Size','Grain Size');
insert into keyval (key, val) values('Soil_Grain_Size','Soil Grain Size');
insert into keyval (key, val) values('Soil_Munsell_Colour','Munsell Colour');
insert into keyval (key, val) values('Soil_Particle_Sorting','Particle Sorting');
insert into keyval (key, val) values('Soil_Particle_Sorting','Soil Particle Sorting');
insert into keyval (key, val) values('Soil_remains_in_ball_when_squeezed','Soil remains in ball when squeezed');
insert into keyval (key, val) values('Soil_Stone_Shape','Stone Shape');
insert into keyval (key, val) values('Soil_Stone_Size','Stone Size');
insert into keyval (key, val) values('Soil_Stoniness','Stoniness');
insert into keyval (key, val) values('Soil_Texture','Material');
insert into keyval (key, val) values('Space','Space');
insert into keyval (key, val) values('Space','Space');
insert into keyval (key, val) values('Space','Space');
insert into keyval (key, val) values('Special_Find','Small Find');
insert into keyval (key, val) values('Special_Finds','Small Finds');
insert into keyval (key, val) values('Spongy','Spongy');
insert into keyval (key, val) values('Square','Square');
insert into keyval (key, val) values('Stakehole','Stakehole');
insert into keyval (key, val) values('Stakehole','Stakehole');
insert into keyval (key, val) values('Stakehole_row','Stakehole row');
insert into keyval (key, val) values('Start.Recording','Start Recording');
insert into keyval (key, val) values('Start_date','Start Date');
insert into keyval (key, val) values('Steeply_sloping','Steeply Sloping');
insert into keyval (key, val) values('Stepped','Stepped');
insert into keyval (key, val) values('Sterile','Sterile');
insert into keyval (key, val) values('Stiff','Stiff');
insert into keyval (key, val) values('Stone','Stone');
insert into keyval (key, val) values('Stones','Stones');
insert into keyval (key, val) values('Stretcher','Stretcher');
insert into keyval (key, val) values('String_courses','String courses');
insert into keyval (key, val) values('Strong_ribbon','Strong ribbon');
insert into keyval (key, val) values('Strongly_cemented','Strongly cemented');
insert into keyval (key, val) values('Structural','Structural');
insert into keyval (key, val) values('Structural_Components','Material Type');
insert into keyval (key, val) values('Structural_Debris','Structural Debris/Collapse');
insert into keyval (key, val) values('Structure','Structure');
insert into keyval (key, val) values('Structure_Description','Structure Description');
insert into keyval (key, val) values('Structure_Shape','Shape in Plan');
insert into keyval (key, val) values('Structure_Shape','Structure Shape');
insert into keyval (key, val) values('Structures','Structures');
insert into keyval (key, val) values('Sub-angular','Sub-angular');
insert into keyval (key, val) values('Sub-Circular','Sub-Circular');
insert into keyval (key, val) values('Sub-rectangular','Sub-rectangular');
insert into keyval (key, val) values('Sub-rounded','Sub-rounded');
insert into keyval (key, val) values('Surface','Surface');
insert into keyval (key, val) values('Tabular','Tabular');
insert into keyval (key, val) values('Tapered','Tapered');
insert into keyval (key, val) values('TASK_Roll_ribbon','TASK: Roll ribbon');
insert into keyval (key, val) values('TASK_Wet_soil_and_rub_with_forefinger','TASK: Wet soil and rub with forefinger');
insert into keyval (key, val) values('Target_A_X','Target A: X');
insert into keyval (key, val) values('Target_A_Y','Target A: Y');
insert into keyval (key, val) values('Target_B_X','Target B: X');
insert into keyval (key, val) values('Target_B_Y','Target B: Y');
insert into keyval (key, val) values('Target_C_X','Target C: X');
insert into keyval (key, val) values('Target_C_Y','Target C: Y');
insert into keyval (key, val) values('Target_D_X','Target D: X');
insert into keyval (key, val) values('Target_D_Y','Target D: Y');
insert into keyval (key, val) values('Terracotta','Terracotta');
insert into keyval (key, val) values('Texture_Helper','Material Helper');
insert into keyval (key, val) values('Thin_Section','Thin Section');
insert into keyval (key, val) values('Timber','Timber');
insert into keyval (key, val) values('Token','Token');
insert into keyval (key, val) values('Truncation','Truncation');
insert into keyval (key, val) values('Underfloor','Underfloor');
insert into keyval (key, val) values('Uneven','Uneven');
insert into keyval (key, val) values('Uneven_courses','Uneven courses');
insert into keyval (key, val) values('Unmortared','Unmortared');
insert into keyval (key, val) values('Unsterilised','Unsterilised');
insert into keyval (key, val) values('User_List','User List');
insert into keyval (key, val) values('USER_LIST','User List');
insert into keyval (key, val) values('Users','Users');
insert into keyval (key, val) values('Vertical','Vertical');
insert into keyval (key, val) values('Very_angular','Very angular');
insert into keyval (key, val) values('Very_soft','Very soft');
insert into keyval (key, val) values('View_Attached_Files','View Attached Files');
insert into keyval (key, val) values('View_Attached_Sketches','View Attached Sketches');
insert into keyval (key, val) values('Volume','Volume (L)');
insert into keyval (key, val) values('Wall','Wall');
insert into keyval (key, val) values('Wavy','Wavy');
insert into keyval (key, val) values('Weak_ribbon','Weak ribbon (less than 2.5cm long)');
insert into keyval (key, val) values('Weakly_cemented','Weakly cemented');
insert into keyval (key, val) values('Well-rounded','Well-rounded');
insert into keyval (key, val) values('Well','Well');
insert into keyval (key, val) values('Wet_Sieve','Wet Sieve');
insert into keyval (key, val) values('Wholly_naturally_derived','Wholly naturally derived');
insert into keyval (key, val) values('Width','Width (m)');
insert into keyval (key, val) values('Wood/Charcoal','Wood/Charcoal');
insert into keyval (key, val) values('Yard','Yard');
insert into keyval (key, val) values('Yard_Fill','Yard Fill');
insert into keyval (key, val) values('Yard_surface','Yard surface');
insert into keyval (key, val) values('Yes','Yes');
insert into keyval (key, val) values('Your_description','Your Description');
insert into keyval (key, val) values('Your_Discussion','Your Interpretation ');
insert into keyval (key, val) values('Your_Interpretation','Your Interpretation');
insert into keyval (key, val) values('Your_Interpretation_Cut_Indeterminate','Indeterminate');
insert into keyval (key, val) values('Your_Interpretation_Structure_Indeterminate','Indeterminate');
insert into keyval (key, val) values('zaOther','Other (add Annotation)');
insert into keyval (key, val) values('zOther','Other');


.mode tabs
select response as 'All Descriptions' from (
select aenttypeid, 0 as attributeid, 0 as vocabid, '# '||aenttypename||'
*'|| coalesce(nullif(aenttypedescription,''),'No Description.') ||'*' as response from aenttype
union
select aenttypeid, attributeid, 0, '  * '||attributename||': '|| attributedescription from attributekey join idealaent using (attributeid) join aenttype using (aenttypeid)
union
select aenttypeid, attributeid, vocabid, '    * '||coalesce(val, vocabname)||' *'||vocabname||'*: '|| COALESCE(vocabdescription,'No Description') from vocabulary left outer join keyval on (vocabname = '{'||key||'}') join attributekey using (attributeid) join idealaent using (attributeid) join aenttype using (aenttypeid)
)
order by aenttypeid, attributeid, vocabid;
